#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - bash
  - bash-completion
  - nano
  - curl
  - wget
  - ca-certificates
  - screen
  - zip
  - unzip
  - htop
  - iotop
  - iftop
  - ufw
  - rsync
  - needrestart
